// F-158: the slash-command registry, explicit and iterable. commandTargetTab in
// protocol.ts routes through this single table, and the registry-coverage test walks
// REGISTERED_SLASH_COMMANDS to prove every registered command path leaves a transcript
// entry (result, queued, or failed) — the silent-swallow branch is banned.
export const COMMAND_TAB_REGISTRY: Readonly<Record<string, string>> = {
  chat: "chat",
  clear: "chat",
  reset: "chat",
  cancel: "chat",
  paste: "chat",
  copy: "chat",
  copylast: "chat",
  thread: "chat",
  help: "chat",
  runtime: "runtime",
  git: "repo",
  model: "models",
  models: "models",
  swarm: "agents",
  agni: "agents",
  gates: "agents",
  witness: "agents",
  openclaw: "agents",
  hum: "agents",
  trishula: "agents",
  evolve: "evolution",
  loops: "evolution",
  cascade: "evolution",
  context: "ontology",
  foundations: "ontology",
  telos: "ontology",
  dharma: "ontology",
  corpus: "ontology",
  evidence: "ontology",
  moltbook: "ontology",
  sessions: "sessions",
  session: "sessions",
  notes: "sessions",
  memory: "sessions",
  archive: "sessions",
  darwin: "sessions",
  logs: "sessions",
  truth: "sessions",
  stigmergy: "sessions",
  approval: "approvals",
  approvals: "approvals",
  permission: "approvals",
  permissions: "approvals",
  status: "control",
  dashboard: "control",
  // F-065 + tour: layout/tour commands are answered locally in submitPrompt
  // (same pattern as the bare /model picker) — they never reach the bridge.
  zen: "chat",
  cockpit: "chat",
  scroll: "chat",
  deck: "chat",
  tour: "chat",
};

export const REGISTERED_SLASH_COMMANDS: readonly string[] = Object.keys(COMMAND_TAB_REGISTRY);
