"""Pure backend engine for the Bun terminal runtime."""

from .events import (
    EVENT_TYPES,
    CanonicalEvent,
    ErrorEvent,
    RateLimitEvent,
    RateLimitEvent as CanonicalRateLimitEvent,
    SessionEnd,
    SessionStart,
    TaskComplete,
    TaskProgress,
    TaskProgress as CanonicalTaskProgress,
    TaskStarted,
    TaskStarted as CanonicalTaskStarted,
    TextComplete,
    TextDelta,
    ThinkingComplete,
    ThinkingDelta,
    ToolArgumentsDelta,
    ToolCallComplete,
    ToolCallStart,
    ToolProgress,
    ToolProgress as CanonicalToolProgress,
    ToolResult,
    ToolResult as CanonicalToolResult,
    UsageReport,
    PermissionDecisionEvent,
    PermissionResolutionEvent,
    PermissionOutcomeEvent,
)
from .governance import GovernanceFilter, GovernancePolicy
from .session_store import SessionStore
from .event_types import (
    AssistantMessage,
    ResultMessage,
    StreamDelta,
    SystemInit,
)
from .stream_parser import parse_ndjson_line

__all__ = [
    "EVENT_TYPES",
    "CanonicalEvent",
    "CanonicalRateLimitEvent",
    "CanonicalTaskProgress",
    "CanonicalTaskStarted",
    "CanonicalToolProgress",
    "CanonicalToolResult",
    "ErrorEvent",
    "GovernanceFilter",
    "GovernancePolicy",
    "RateLimitEvent",
    "SessionEnd",
    "SessionStart",
    "SessionStore",
    "TaskComplete",
    "TaskProgress",
    "TaskStarted",
    "TextComplete",
    "TextDelta",
    "ThinkingComplete",
    "ThinkingDelta",
    "ToolArgumentsDelta",
    "ToolCallComplete",
    "ToolCallStart",
    "ToolProgress",
    "ToolResult",
    "UsageReport",
    "PermissionDecisionEvent",
    "PermissionResolutionEvent",
    "PermissionOutcomeEvent",
    "AssistantMessage",
    "ResultMessage",
    "StreamDelta",
    "SystemInit",
    "parse_ndjson_line",
]
