"""Shared operator-core contracts for the DGC shells.

This package is the shell-neutral foundation for the Bun TUI and dashboard UI.
It does not own rendering concerns. It owns the canonical shapes that both
shells must agree on when they talk about sessions, runtime truth, entities,
permissions, and orchestration state.
"""

from .adapters import (
    event_envelope_from_legacy_event,
    permission_decision_from_tool_call,
    routing_decision_from_policy,
    runtime_snapshot_from_operator_snapshot,
    session_from_meta,
)
from .permissions import GovernanceFilter, GovernancePolicy
from .permission_payloads import (
    build_permission_decision_payload,
    build_permission_history_payload,
    build_permission_outcome_payload,
    build_permission_resolution_payload,
    permission_decision_payload_from_decision,
    permission_outcome_payload_from_outcome,
    permission_resolution_payload_from_resolution,
)
from .command_payloads import build_command_graph_summary, build_command_registry_payload
from .command_spine import (
    AgentOpsReportSummary,
    AgentOpsReview,
    CoherenceDelta,
    HumanYDSRating,
    MissionAttachment,
    OperatorCommandPlan,
    OperatorCommandRequest,
    PlannedSubTask,
    PromptIntent,
    RustReadinessDecision,
    RustReadinessSignal,
    WorkPacketDraft,
    evaluate_rust_readiness,
    plan_operator_command,
    plan_to_dict,
    record_human_yds_rating,
    resolve_prompt_intent,
    review_agentops_reports,
    work_packet_to_dict,
)
from .operating_facts import (
    AgentOpsRunFact,
    BurnReportFact,
    HumanQualityRatingFact,
    KaizenReviewFact,
    OperatingFactBundle,
    OperatingFactInputs,
    OrganBoundary,
    OrganStateFact,
    RevenueSignalFact,
    append_human_yds_rating,
    build_operating_fact_bundle,
    bundle_to_dict,
    coherence_map_to_dict,
    load_agentops_run_facts,
    load_burn_report_facts,
    load_human_yds_rating_facts,
    load_kaizen_review_facts,
    load_revenue_signal_facts,
    organ_boundary_map,
    organ_state_facts,
    rust_membrane_candidates,
)
from .routing_payloads import build_agent_routes_payload, build_model_policy_summary, build_routing_decision_payload
from .routing_manifest_payloads import (
    build_routing_manifest_payload,
    normalize_adapter_catalog,
    normalize_agent_assignments,
    normalize_legacy_targets,
)
from .runtime_payloads import build_runtime_snapshot_payload
from .workspace_payloads import build_workspace_snapshot_payload
from .session_payloads import build_session_catalog_payload, build_session_detail_payload
from .session_store import SessionStore, cwd_matches
from .session_views import build_session_catalog, build_session_detail
from .contracts import (
    CanonicalEntity,
    CanonicalEventEnvelope,
    CanonicalPermissionDecision,
    CanonicalPermissionResolution,
    CanonicalRelation,
    CanonicalRoutingDecision,
    CanonicalRuntimeSnapshot,
    CanonicalSession,
    CanonicalWorkflowState,
    EntityBadge,
    EntityRef,
    EventAudience,
    EventSource,
    EventTransport,
    PermissionDecisionKind,
    PermissionResolutionKind,
    PermissionRisk,
    RuntimeHealth,
    WorkflowExecutionMode,
)

__all__ = [
    "AgentOpsReportSummary",
    "AgentOpsReview",
    "AgentOpsRunFact",
    "BurnReportFact",
    "CanonicalEntity",
    "CanonicalEventEnvelope",
    "CanonicalPermissionDecision",
    "CanonicalPermissionResolution",
    "CanonicalRelation",
    "CanonicalRoutingDecision",
    "CanonicalRuntimeSnapshot",
    "CanonicalSession",
    "CanonicalWorkflowState",
    "CoherenceDelta",
    "EntityBadge",
    "EntityRef",
    "EventAudience",
    "EventSource",
    "EventTransport",
    "GovernanceFilter",
    "GovernancePolicy",
    "HumanYDSRating",
    "HumanQualityRatingFact",
    "KaizenReviewFact",
    "MissionAttachment",
    "OperatorCommandPlan",
    "OperatorCommandRequest",
    "OperatingFactBundle",
    "OperatingFactInputs",
    "OrganBoundary",
    "OrganStateFact",
    "PlannedSubTask",
    "PromptIntent",
    "RevenueSignalFact",
    "append_human_yds_rating",
    "build_operating_fact_bundle",
    "build_permission_decision_payload",
    "build_permission_history_payload",
    "build_permission_outcome_payload",
    "build_permission_resolution_payload",
    "build_command_graph_summary",
    "build_command_registry_payload",
    "build_agent_routes_payload",
    "build_model_policy_summary",
    "build_routing_decision_payload",
    "build_routing_manifest_payload",
    "build_runtime_snapshot_payload",
    "build_workspace_snapshot_payload",
    "evaluate_rust_readiness",
    "PermissionDecisionKind",
    "PermissionResolutionKind",
    "PermissionRisk",
    "RuntimeHealth",
    "RustReadinessDecision",
    "RustReadinessSignal",
    "SessionStore",
    "WorkflowExecutionMode",
    "WorkPacketDraft",
    "build_session_catalog",
    "build_session_catalog_payload",
    "build_session_detail",
    "build_session_detail_payload",
    "bundle_to_dict",
    "coherence_map_to_dict",
    "cwd_matches",
    "event_envelope_from_legacy_event",
    "permission_decision_from_tool_call",
    "permission_decision_payload_from_decision",
    "permission_outcome_payload_from_outcome",
    "permission_resolution_payload_from_resolution",
    "load_agentops_run_facts",
    "load_burn_report_facts",
    "load_human_yds_rating_facts",
    "load_kaizen_review_facts",
    "load_revenue_signal_facts",
    "routing_decision_from_policy",
    "normalize_adapter_catalog",
    "normalize_agent_assignments",
    "normalize_legacy_targets",
    "organ_boundary_map",
    "organ_state_facts",
    "runtime_snapshot_from_operator_snapshot",
    "rust_membrane_candidates",
    "plan_operator_command",
    "plan_to_dict",
    "record_human_yds_rating",
    "resolve_prompt_intent",
    "review_agentops_reports",
    "session_from_meta",
    "work_packet_to_dict",
]
