#!/usr/bin/env python3
"""Generate scenicArt.ts — Hokusai's Great Wave as half-block truecolor cells.

Replaces the hand-typed glyph mosaic that shattered on the operator's font
(design truth finding 19). Technique: each terminal cell renders U+2580 UPPER
HALF BLOCK with foreground = top pixel, background = bottom pixel — one glyph
with universal font coverage; 24-bit color does all the painting. Edges fade
into the night canvas (#10141C) so the band sits on the theme instead of
floating as a slab (design truth ScenicStrip landmine).

Usage: python3 scripts/scenic_generate.py <source.jpg> > src/components/scenicArt.ts
Deterministic for a given source image + constants; the emitted file is data.
"""

import json
import sys

from PIL import Image

NIGHT = (0x10, 0x14, 0x1C)
WIDTHS = (118, 98, 78)
ROWS = 9  # 18 pixel rows per variant

# Crop band: the wave crest with Fuji in the trough — the iconic section.
# Tuned for the 1280x883 Wikimedia scan.
CROP = (0, 130, 1280, 560)

EDGE_FADE_COLS = 10
TOP_FADE_ROWS = 3


def lerp(a: tuple, b: tuple, t: float) -> tuple:
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def hexc(c: tuple) -> str:
    return "#{:02x}{:02x}{:02x}".format(*c)


def build(width: int, src: Image.Image) -> list:
    px_w, px_h = width, ROWS * 2
    img = src.resize((px_w, px_h), Image.LANCZOS).convert("RGB")
    pixels = img.load()

    def faded(x: int, y: int) -> tuple:
        c = pixels[x, y]
        t = 0.0
        if x < EDGE_FADE_COLS:
            t = max(t, 1.0 - x / EDGE_FADE_COLS)
        if x >= px_w - EDGE_FADE_COLS:
            t = max(t, 1.0 - (px_w - 1 - x) / EDGE_FADE_COLS)
        if y < TOP_FADE_ROWS:
            t = max(t, (1.0 - y / TOP_FADE_ROWS) * 0.85)
        return lerp(c, NIGHT, min(t, 1.0)) if t > 0 else c

    rows = []
    for row in range(ROWS):
        segments = []
        run = None
        for x in range(px_w):
            fg = hexc(faded(x, row * 2))
            bg = hexc(faded(x, row * 2 + 1))
            if run and run["fg"] == fg and run["bg"] == bg:
                run["n"] += 1
            else:
                run = {"fg": fg, "bg": bg, "n": 1}
                segments.append(run)
        rows.append(segments)
    return rows


def main() -> None:
    src = Image.open(sys.argv[1]).crop(CROP)
    variants = {str(w): build(w, src) for w in WIDTHS}
    print("// GENERATED by scripts/scenic_generate.py — do not hand-edit.")
    print("// Hokusai, The Great Wave off Kanagawa (public domain), as")
    print("// half-block truecolor cells. Data, not styling: theme law exempt.")
    print("export type ScenicSegment = {fg: string; bg: string; n: number};")
    print("export const SCENIC_ROWS = %d;" % ROWS)
    print(
        "export const SCENIC_VARIANTS: Record<string, ScenicSegment[][]> = "
        + json.dumps(variants, separators=(",", ":"))
        + ";"
    )
    print("export const SCENIC_WIDTHS = %s;" % list(WIDTHS))


if __name__ == "__main__":
    main()
