"""Morning briefing → strategic build spec (the synthesis→action seam).

Reads the latest ``~/.dharma/sessions/captures/daily/<date>/morning_briefing.md``,
extracts the ``## The single most important move for today`` section, and
emits a build spec that ``tools.build_protocol.pilot00_dryrun_generator``
can consume.

The seam closes the gap from "the mind named the move" to
"the protocol can dispatch it." It auto-fills what it can extract with
high confidence and leaves explicit ``TODO`` markers everywhere a human
must decide. ``pilot00_dryrun_generator`` rejects specs containing
``TODO``/``TBD``/``I don't know``, so this enforces the human-approval gate
without a separate signing step.

This module is read-only relative to source: it writes only into
``~/.dharma/build_protocol/specs/`` and prints the resulting path.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Sequence


DEFAULT_FORBIDDEN_PATHS: tuple[str, ...] = (
    "dharma_swarm/orchestrate_live.py",
    "dharma_swarm/swarm.py",
    "dharma_swarm/frontier_council.py",
    "dharma_swarm/agent_runner.py",
    "dharma_swarm/guardian_crew.py",
    "dharma_swarm/insight_brief.py",
    "api/**",
    "dashboard/**",
)

# Heuristic patterns for extracting structure from briefing prose.
_PATH_PATTERN = re.compile(
    r"`(?P<path>(?:~/[^`\s]+|/[^`\s]+|\.[/.][^`\s]+|[A-Za-z][\w/.-]+\.(?:py|md|sh|json|yaml|yml|toml|ts|tsx|js)))`"
)
_LOC_PATTERN = re.compile(r"~?\s*(?P<n>\d+)\s*(?:LOC|loc|lines?)\b")
_CMD_PATTERN = re.compile(
    r"`(?P<cmd>(?:python(?:3)?\s|pytest\s|chetana\s|dgc\s|make\s|bash\s|npm\s|node\s|gh\s)[^`]+)`"
)
_HOT_FILE_BASENAMES = {
    "orchestrate_live.py", "swarm.py", "frontier_council.py",
    "agent_runner.py", "guardian_crew.py", "insight_brief.py",
}


@dataclass(frozen=True)
class ExtractedMove:
    """What we could pull from the briefing's most-important-move section."""
    headline: str
    body: str
    target_paths: tuple[str, ...]
    loc_estimate: int | None
    proof_commands: tuple[str, ...]
    hot_file_warnings: tuple[str, ...]


def find_latest_briefing(
    daily_root: Path | None = None,
    *,
    today: date | None = None,
) -> Path:
    """Return the most recent morning_briefing.md, scanning today first then back."""
    daily_root = (daily_root or Path.home() / ".dharma" / "sessions" / "captures" / "daily").expanduser()
    today = today or date.today()
    if not daily_root.is_dir():
        raise FileNotFoundError(f"daily captures dir missing: {daily_root}")
    candidates = sorted(
        (p for p in daily_root.iterdir() if p.is_dir() and p.name >= "2020-01-01"),
        reverse=True,
    )
    for day_dir in candidates:
        brief = day_dir / "morning_briefing.md"
        if brief.is_file() and brief.stat().st_size > 0:
            return brief
    raise FileNotFoundError(f"no non-empty morning_briefing.md under {daily_root}")


def extract_move(briefing_text: str) -> ExtractedMove:
    """Pull the most-important-move section out of a briefing."""
    section = _extract_section(
        briefing_text,
        ("The single most important move for today", "Most important move", "Single most important move"),
    )
    if not section:
        raise ValueError("briefing has no 'most important move' section")

    headline, body = _split_headline_body(section)
    paths = _collect(_PATH_PATTERN, section, "path")
    cmds = _collect(_CMD_PATTERN, section, "cmd")
    loc_match = _LOC_PATTERN.search(section)
    loc = int(loc_match.group("n")) if loc_match else None
    hot = tuple(p for p in paths if Path(p).name in _HOT_FILE_BASENAMES)
    return ExtractedMove(
        headline=headline.strip(),
        body=body.strip(),
        target_paths=paths,
        loc_estimate=loc,
        proof_commands=cmds,
        hot_file_warnings=hot,
    )


def render_spec(
    move: ExtractedMove,
    *,
    briefing_path: Path,
    today: date | None = None,
) -> str:
    """Render a spec.md compatible with pilot00_dryrun_generator."""
    today = today or date.today()
    slug = _slug_from_headline(move.headline) or "brief-move"
    title = f"brief-{today.isoformat()}-{slug}"
    telos = move.headline or "TODO: state the telos in one sentence"
    allowed = move.target_paths or ("TODO: list allowed paths",)
    proof = move.proof_commands[0] if move.proof_commands else "TODO: single deterministic proof command"
    forbidden_extra = ()
    hot_block = "\n".join(f"- {p}" for p in move.hot_file_warnings) if move.hot_file_warnings else ""

    lines: list[str] = [
        f"# {title}",
        "",
        "<!-- Generated by tools/build_protocol/brief_to_spec.py.",
        f"     Source briefing: {briefing_path}",
        f"     Generated at: {datetime.now().isoformat(timespec='seconds')}",
        "     Replace every TODO before running `dharma-build plan`. -->",
        "",
        f"Telos: {telos}",
        "",
        "Allowed paths:",
    ]
    lines += [f"- {p}" for p in allowed]
    lines += ["", "Forbidden paths:"]
    lines += [f"- {p}" for p in (*DEFAULT_FORBIDDEN_PATHS, *forbidden_extra)]
    if hot_block:
        lines += ["", "Hot files:"]
        lines += [f"- {p}" for p in move.hot_file_warnings]
        lines += [
            "",
            "<!-- WARNING: hot file in scope. Confirm explicit human approval. -->",
        ]
    lines += [
        "",
        f"Proof command: {proof}",
        "",
        "Reviewer: TODO: name the reviewer agent (must differ from builder)",
        "",
        "## Briefing context (read-only quote)",
        "",
        "> " + move.headline.replace("\n", "\n> "),
        "",
        move.body,
        "",
    ]
    if move.loc_estimate:
        lines += [f"<!-- Estimated change size: ~{move.loc_estimate} LOC. -->", ""]
    return "\n".join(lines)


def write_spec(
    spec_text: str,
    *,
    output_dir: Path | None = None,
    title_slug: str | None = None,
    today: date | None = None,
) -> Path:
    """Write spec_text to ~/.dharma/build_protocol/specs/<date>-<slug>.md."""
    today = today or date.today()
    output_dir = (output_dir or Path.home() / ".dharma" / "build_protocol" / "specs").expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = title_slug or "brief-move"
    out_path = output_dir / f"{today.isoformat()}-{slug}.md"
    out_path.write_text(spec_text, encoding="utf-8")
    return out_path


def brief_to_spec(
    *,
    briefing_path: Path | None = None,
    output_dir: Path | None = None,
    today: date | None = None,
) -> Path:
    """End-to-end: find latest briefing, extract move, write spec, return path."""
    briefing_path = briefing_path.expanduser().resolve() if briefing_path else find_latest_briefing(today=today)
    text = briefing_path.read_text(encoding="utf-8")
    move = extract_move(text)
    spec_text = render_spec(move, briefing_path=briefing_path, today=today)
    slug = _slug_from_headline(move.headline) or "brief-move"
    return write_spec(spec_text, output_dir=output_dir, title_slug=slug, today=today)


def _extract_section(text: str, headers: Sequence[str]) -> str:
    for h in headers:
        pattern = re.compile(
            rf"^##\s+{re.escape(h)}\s*$(?P<body>.*?)(?=^##\s|\Z)",
            re.MULTILINE | re.DOTALL,
        )
        m = pattern.search(text)
        if m:
            return m.group("body")
    return ""


def _split_headline_body(section: str) -> tuple[str, str]:
    stripped = section.strip()
    if not stripped:
        return "", ""
    paragraphs = re.split(r"\n\s*\n", stripped, maxsplit=1)
    headline_para = paragraphs[0]
    body = paragraphs[1] if len(paragraphs) > 1 else ""
    headline = re.sub(r"^\*\*|\*\*$|^>\s*", "", headline_para.strip())
    headline = headline.replace("**", "").strip()
    return headline, body


def _collect(pattern: re.Pattern[str], text: str, group: str) -> tuple[str, ...]:
    seen: list[str] = []
    for m in pattern.finditer(text):
        v = m.group(group).strip()
        if v and v not in seen:
            seen.append(v)
    return tuple(seen)


def _slug_from_headline(headline: str) -> str:
    cleaned = re.sub(r"`[^`]+`", " ", headline).lower()
    cleaned = re.sub(r"[^a-z0-9]+", "-", cleaned)
    cleaned = cleaned.strip("-")
    return cleaned[:48] if cleaned else ""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="brief-to-spec", description=__doc__)
    parser.add_argument("--briefing", type=Path, default=None, help="path to a morning_briefing.md (default: latest)")
    parser.add_argument("--output-dir", type=Path, default=None, help="override output dir")
    parser.add_argument("--print", action="store_true", help="print spec to stdout instead of writing")
    args = parser.parse_args(argv)

    briefing = args.briefing.expanduser().resolve() if args.briefing else find_latest_briefing()
    text = briefing.read_text(encoding="utf-8")
    move = extract_move(text)
    spec_text = render_spec(move, briefing_path=briefing)
    if args.print:
        print(spec_text)
        return 0
    out = write_spec(
        spec_text,
        output_dir=args.output_dir,
        title_slug=_slug_from_headline(move.headline) or "brief-move",
    )
    print(out)
    if "TODO" in spec_text:
        print(
            "spec contains TODOs — edit those before invoking `dharma-build plan`",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
