"""Opportunity board entry -> strategic build spec.

This is the opportunity-side sibling of ``brief_to_spec``. It reads one
selected ``opportunity_board.json`` row and emits the same markdown spec shape
that ``pilot00_dryrun_generator`` already consumes. It does not create packets,
spawn agents, create worktrees, edit source, or invent a second packet format.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any, Sequence

from tools.build_protocol.brief_to_spec import DEFAULT_FORBIDDEN_PATHS


_PATH_PATTERN = re.compile(
    r"(?P<path>(?:~/[^\s`]+|/[^\s`]+|\.[/.][^\s`]+|[A-Za-z][\w/.-]+\.(?:py|md|sh|json|yaml|yml|toml|ts|tsx|js)))"
)
_HOT_FILE_BASENAMES = {
    "orchestrate_live.py",
    "swarm.py",
    "frontier_council.py",
    "agent_runner.py",
    "guardian_crew.py",
    "insight_brief.py",
}


@dataclass(frozen=True)
class SelectedOpportunity:
    """One normalized row from opportunity_board.json."""

    row: dict[str, Any]
    board_path: Path
    index: int

    @property
    def opportunity_id(self) -> str:
        return str(self.row.get("opportunity_id") or f"opportunity_{self.index + 1}")

    @property
    def title(self) -> str:
        return str(self.row.get("title") or self.opportunity_id).strip()


def load_opportunity_board(board_path: Path | None = None) -> list[dict[str, Any]]:
    """Load opportunity_board.json as a list of row dicts."""
    path = _board_path(board_path)
    raw = json.loads(path.read_text(encoding="utf-8") or "[]")
    if not isinstance(raw, list):
        raise ValueError(f"opportunity board is not a list: {path}")
    return [row for row in raw if isinstance(row, dict)]


def select_opportunity(
    rows: Sequence[dict[str, Any]],
    *,
    board_path: Path,
    opportunity_id: str | None = None,
    index: int = 0,
) -> SelectedOpportunity:
    """Select a board row by id or zero-based index."""
    if opportunity_id:
        for idx, row in enumerate(rows):
            if str(row.get("opportunity_id") or "") == opportunity_id:
                return SelectedOpportunity(row=row, board_path=board_path, index=idx)
        raise ValueError(f"opportunity_id not found: {opportunity_id}")
    if index < 0 or index >= len(rows):
        raise IndexError(f"opportunity index out of range: {index}")
    return SelectedOpportunity(row=rows[index], board_path=board_path, index=index)


def render_spec(
    selected: SelectedOpportunity,
    *,
    today: date | None = None,
) -> str:
    """Render a Pilot-00-compatible markdown spec from one opportunity row."""
    today = today or date.today()
    row = selected.row
    title = selected.title
    opp_id = selected.opportunity_id
    domain = str(row.get("domain") or "unknown")
    thesis = str(row.get("thesis") or "opportunity")
    why_now = str(row.get("why_now") or "")
    score = row.get("final_score")
    telos = f"{title} - {thesis}"
    allowed = _infer_allowed_paths(row) or ("TODO: list allowed paths",)
    hot_files = tuple(path for path in allowed if Path(path).name in _HOT_FILE_BASENAMES)
    slug = _slugify(f"opportunity-{opp_id}-{title}")

    lines: list[str] = [
        f"# opportunity-{today.isoformat()}-{slug}",
        "",
        "<!-- Generated by tools/build_protocol/opportunity_to_spec.py.",
        f"     Source board: {selected.board_path}",
        f"     Opportunity id: {opp_id}",
        f"     Generated at: {datetime.now().isoformat(timespec='seconds')}",
        "     Replace every TODO before running `dharma-build plan`. -->",
        "",
        f"Telos: {telos}",
        "",
        "Allowed paths:",
    ]
    lines += [f"- {path}" for path in allowed]
    lines += ["", "Forbidden paths:"]
    lines += [f"- {path}" for path in DEFAULT_FORBIDDEN_PATHS]
    if hot_files:
        lines += ["", "Hot files:"]
        lines += [f"- {path}" for path in hot_files]
        lines += ["", "<!-- WARNING: hot file in scope. Confirm explicit human approval. -->"]
    lines += [
        "",
        "Proof command: TODO: single deterministic proof command",
        "",
        "Reviewer: TODO: name the reviewer agent (must differ from builder)",
        "",
        "## Opportunity context",
        "",
        f"- opportunity_id: {opp_id}",
        f"- domain: {domain}",
        f"- thesis: {thesis}",
        f"- final_score: {score}",
        f"- why_now: {why_now}",
        "",
        "## Evidence signals",
        "",
    ]
    evidence = [str(item) for item in list(row.get("evidence_signals") or [])]
    if evidence:
        lines += [f"- {item}" for item in evidence]
    else:
        lines += ["- No evidence signals present in board row."]
    source_inputs = [source for source in list(row.get("source_inputs") or []) if isinstance(source, dict)]
    if source_inputs:
        lines += ["", "## Source inputs", ""]
        for source in source_inputs[:12]:
            source_name = str(source.get("source") or "unknown")
            evidence_ref = str(source.get("evidence_ref") or "")
            title = str(source.get("title") or source.get("category") or "")
            suffix = f" - {title}" if title else ""
            lines.append(f"- {source_name}: {evidence_ref}{suffix}".rstrip())
    return "\n".join(lines).rstrip() + "\n"


def write_spec(
    spec_text: str,
    *,
    output_dir: Path | None = None,
    title_slug: str,
    today: date | None = None,
) -> Path:
    """Write spec_text to ~/.dharma/build_protocol/specs/<date>-<slug>.md."""
    today = today or date.today()
    output_dir = (output_dir or Path.home() / ".dharma" / "build_protocol" / "specs").expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{today.isoformat()}-{title_slug}.md"
    out_path.write_text(spec_text, encoding="utf-8")
    return out_path


def opportunity_to_spec(
    *,
    board_path: Path | None = None,
    output_dir: Path | None = None,
    opportunity_id: str | None = None,
    index: int = 0,
    today: date | None = None,
) -> Path:
    """End-to-end: select one opportunity, write spec, return path."""
    resolved_board = _board_path(board_path)
    rows = load_opportunity_board(resolved_board)
    selected = select_opportunity(
        rows,
        board_path=resolved_board,
        opportunity_id=opportunity_id,
        index=index,
    )
    spec_text = render_spec(selected, today=today)
    return write_spec(
        spec_text,
        output_dir=output_dir,
        title_slug=_slugify(f"opportunity-{selected.opportunity_id}-{selected.title}") or "opportunity",
        today=today,
    )


def spec_needs_operator_completion(spec_text: str) -> bool:
    """Return True when operator-owned pre-flight fields still contain placeholders."""
    for line in spec_text.splitlines():
        stripped = line.strip()
        if stripped.startswith(("Telos:", "Proof command:", "Reviewer:", "- TODO:")):
            if re.search(r"\b(TODO|TBD)\b|i don't know", stripped, re.IGNORECASE):
                return True
    return False


def _board_path(board_path: Path | None = None) -> Path:
    return (board_path or Path.home() / ".dharma" / "meta" / "opportunity_board.json").expanduser()


def _infer_allowed_paths(row: dict[str, Any]) -> tuple[str, ...]:
    text_parts: list[str] = []
    for key in ("title", "thesis", "why_now"):
        text_parts.append(str(row.get(key) or ""))
    text_parts.extend(str(item) for item in list(row.get("evidence_signals") or []))
    for source in list(row.get("source_inputs") or []):
        if isinstance(source, dict):
            text_parts.append(str(source.get("evidence_ref") or ""))
    seen: list[str] = []
    for match in _PATH_PATTERN.finditer("\n".join(text_parts)):
        path = match.group("path").rstrip(".,);]")
        if path and path not in seen:
            seen.append(path)
    return tuple(seen[:6])


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug[:64]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="opportunity-to-spec",
        description=__doc__,
    )
    parser.add_argument("--board", type=Path, default=None)
    parser.add_argument("--opportunity-id", default=None)
    parser.add_argument("--index", type=int, default=0)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--print", action="store_true")
    args = parser.parse_args(argv)

    resolved_board = _board_path(args.board)
    rows = load_opportunity_board(resolved_board)
    selected = select_opportunity(
        rows,
        board_path=resolved_board,
        opportunity_id=args.opportunity_id,
        index=args.index,
    )
    spec_text = render_spec(selected)
    if args.print:
        print(spec_text, end="")
        return 0
    out = write_spec(
        spec_text,
        output_dir=args.output_dir,
        title_slug=_slugify(f"opportunity-{selected.opportunity_id}-{selected.title}") or "opportunity",
    )
    print(out)
    if spec_needs_operator_completion(spec_text):
        print(
            "spec contains TODOs - edit those before invoking `dharma-build plan`",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
