"""Tests for the SeatedCheckpoint and the fail-CLOSED flips (H02 Phase 4).

THE ONE TEST THAT MATTERS (handoff P4): kill the checkpoint mid-decision —
the system must HOLD and escalate, never proceed.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

import pytest

from dharma_swarm.dharma_attractor import DharmaAttractor, SeatedCheckpoint


@pytest.fixture
def seat(tmp_path):
    return SeatedCheckpoint(escalation_dir=tmp_path, timeout_seconds=5.0)


def _escalations(tmp_path: Path) -> list[dict]:
    records: list[dict] = []
    for f in tmp_path.glob("escalations_*.jsonl"):
        for line in f.read_text().splitlines():
            records.append(json.loads(line))
    return records


class TestKillTheCheckpoint:
    async def test_occupant_killed_mid_decision_holds_and_escalates(
        self, seat, tmp_path
    ):
        async def dead(*a, **k):
            raise ConnectionError("occupant killed mid-decision")

        seat._ask_occupant = dead
        verdict = await seat.review("Mutate parameter X", context_label="kill")
        assert verdict.proceed is False
        recs = _escalations(tmp_path)
        assert recs and "occupant unreachable" in recs[0]["reason"]
        assert recs[0]["context"] == "kill"

    async def test_occupant_hang_times_out_to_hold(self, tmp_path):
        seat = SeatedCheckpoint(escalation_dir=tmp_path, timeout_seconds=0.2)

        async def hung(*a, **k):
            await asyncio.sleep(30)

        seat._ask_occupant = hung
        verdict = await seat.review("Mutate parameter Y", context_label="hang")
        assert verdict.proceed is False, "slowness must equal HOLD"
        assert _escalations(tmp_path)

    async def test_ambiguous_reply_holds_and_escalates(self, seat, tmp_path):
        async def mumble(*a, **k):
            return "WELL, IT DEPENDS ON THE CONTEXT"

        seat._ask_occupant = mumble
        verdict = await seat.review("Mutate parameter Z")
        assert verdict.proceed is False
        assert any("not binary" in r["reason"] for r in _escalations(tmp_path))

    async def test_explicit_hold_holds_without_escalation(self, seat, tmp_path):
        async def hold(*a, **k):
            return "HOLD"

        seat._ask_occupant = hold
        verdict = await seat.review("Suspicious proposal")
        assert verdict.proceed is False
        # A seen-and-held proposal is a verdict, not an escalation.
        assert _escalations(tmp_path) == []

    async def test_proceed_path(self, seat):
        async def yes(*a, **k):
            return "PROCEED"

        seat._ask_occupant = yes
        verdict = await seat.review("Benign proposal")
        assert verdict.proceed is True

    async def test_escalation_write_failure_does_not_crash(self, tmp_path):
        # Escalation dir is an unwritable path (a file, not a dir).
        blocker = tmp_path / "blocked"
        blocker.write_text("not a dir")

        seat = SeatedCheckpoint(escalation_dir=blocker, timeout_seconds=1.0)

        async def dead(*a, **k):
            raise RuntimeError("boom")

        seat._ask_occupant = dead
        verdict = await seat.review("anything")
        assert verdict.proceed is False  # still HOLDs even if escalation I/O fails


class TestOccupantFamilyExclusion:
    async def test_generator_family_is_excluded(self, seat, monkeypatch):
        chosen: list[str] = []

        class _Cfg:
            def __init__(self, model):
                self.default_model = model

        def fake_configs(**kwargs):
            return [_Cfg("qwen3-coder:free"), _Cfg("kimi-k2.6:free")]

        class _Resp:
            content = "PROCEED"

        class _Provider:
            def __init__(self, cfg):
                self._cfg = cfg

            async def complete(self, request):
                chosen.append(request.model)
                return _Resp()

        import dharma_swarm.runtime_provider as rp

        monkeypatch.setattr(
            rp, "preferred_runtime_provider_configs", fake_configs
        )
        monkeypatch.setattr(rp, "create_runtime_provider", _Provider)

        verdict = await seat.review(
            "proposal generated by qwen", exclude_model_tokens=("qwen",)
        )
        assert verdict.proceed is True
        assert chosen == ["kimi-k2.6:free"], "qwen occupant must be skipped"


class TestFailDirectionFlips:
    def test_gnani_checkpoint_holds_when_checker_breaks(self, monkeypatch):
        attractor = DharmaAttractor()

        def broken(*a, **k):
            raise RuntimeError("checker broke")

        monkeypatch.setattr(attractor, "_deterministic_check", broken)
        verdict = attractor.gnani_checkpoint("any proposal")
        assert verdict.proceed is False, "checker failure must HOLD (was fail-open)"

    def test_economic_acceptance_fail_direction_is_closed(self):
        # Source-contract check: the gnani leg of telos_gated_accept must
        # hold on witness error, never fail-open. (Full acceptance-flow
        # scaffolding lives in test_economic_agent.py; this guards the flip.)
        import inspect

        import dharma_swarm.economic_agent as ea

        src = inspect.getsource(ea.telos_gated_accept)
        assert "gnani_passed = False" in src
        assert "gnani_passed = True  # fail-open" not in src

    def test_strange_loop_fail_direction_is_closed(self):
        import inspect

        import dharma_swarm.strange_loop as sl

        src = inspect.getsource(sl.StrangeLoop)
        assert "held_by_gnani_error" in src
        assert "# Gnani error → proceed" not in src

    def test_heartbeat_timeout_fail_direction_is_closed(self):
        import inspect

        import dharma_swarm.swarm as sw

        src = inspect.getsource(sw.SwarmManager)
        assert "HOLDING dispatch" in src
