from __future__ import annotations

import json

from scripts.vibegate_audit import build_report, render_markdown, write_outputs


def test_vibegate_detects_ai_app_launch_blockers(tmp_path):
    app = tmp_path / "lovable-app"
    src = app / "src"
    src.mkdir(parents=True)
    (app / "package.json").write_text(
        json.dumps(
            {
                "dependencies": {
                    "vite": "^7.0.0",
                    "@supabase/supabase-js": "^2.0.0",
                }
            }
        ),
        encoding="utf-8",
    )
    (app / "README.md").write_text("Generated by Lovable.\n", encoding="utf-8")
    fake_openai_key = "sk-" + ("a" * 30)  # built at runtime so source has no literal key shape
    (app / ".env").write_text(f"OPENAI_API_KEY={fake_openai_key}\n", encoding="utf-8")
    (src / "App.tsx").write_text(
        """
        export function App({ html, token }) {
          localStorage.setItem("token", token)
          document.body.innerHTML = html
          return null
        }
        """,
        encoding="utf-8",
    )
    (app / "schema.sql").write_text(
        """
        create table profiles (
          id uuid primary key,
          email text
        );
        """,
        encoding="utf-8",
    )

    report = build_report(app, generated_at="2026-05-04T00:00:00Z")

    assert report.launch_verdict == "do_not_launch"
    assert report.severity_counts["critical"] >= 1
    assert report.severity_counts["high"] >= 2
    assert "lovable-generated" in report.generated_app_signals
    assert "supabase" in report.generated_app_signals
    assert {finding.rule_id for finding in report.findings} >= {
        "secret.env-file",
        "secret.openai-key",
        "web.xss-dangerous-html",
        "web.localstorage-token",
        "supabase.rls-missing-policy",
    }


def test_vibegate_report_is_deterministic_for_same_files(tmp_path):
    app = tmp_path / "bolt-app"
    app.mkdir()
    (app / "package.json").write_text(
        '{"dependencies":{"next":"latest"},"scripts":{"test":"echo ok"}}\n',
        encoding="utf-8",
    )
    (app / "package-lock.json").write_text('{"lockfileVersion":3}\n', encoding="utf-8")
    (app / "README.md").write_text("Generated by Bolt.new\n", encoding="utf-8")

    first = build_report(app, generated_at="2026-05-04T00:00:00Z")
    second = build_report(app, generated_at="2026-05-04T00:00:00Z")

    assert first == second
    assert first.launch_verdict == "launch_ready_static_pass"
    assert first.generated_app_signals == ["bolt-generated", "nextjs", "node-app"]


def test_vibegate_writes_only_configured_outputs(tmp_path):
    app = tmp_path / "clean-app"
    out = tmp_path / "out"
    app.mkdir()
    (app / "package.json").write_text('{"dependencies":{"vite":"latest"}}\n', encoding="utf-8")

    report = build_report(app, generated_at="2026-05-04T00:00:00Z")
    json_path, md_path = write_outputs(report, out)

    assert json_path.parent == out
    assert md_path.parent == out
    assert json.loads(json_path.read_text(encoding="utf-8"))["launch_verdict"] == report.launch_verdict
    assert "VibeGate Launch Hardening Report" in md_path.read_text(encoding="utf-8")


def test_vibegate_markdown_names_concrete_fix(tmp_path):
    app = tmp_path / "python-app"
    app.mkdir()
    (app / "main.py").write_text(
        """
        import subprocess

        def run(cmd):
            return subprocess.run(cmd, shell=True)
        """,
        encoding="utf-8",
    )

    report = build_report(app, generated_at="2026-05-04T00:00:00Z")
    markdown = render_markdown(report)

    assert report.launch_verdict == "launch_with_fix_pr_first"
    assert "python.subprocess-shell" in markdown
    assert "Pass a list of arguments" in markdown
