"""MemoryKernel registry and read-only census primitives.

M0 is intentionally a surface census, not a new memory store.  The package
exposes a stable registry plus bounded probes so later adapters can connect the
existing memory ecosystem without confusing raw evidence, projections, and
canon.
"""

from dharma_swarm.memory_kernel.atoms import (
    AdapterMode,
    AuthorityLevel,
    MemoryAtom,
    MemoryAtomType,
    MemoryLane,
    MemoryOrder,
    MemoryQuery,
    MemoryScope,
    MemorySurface,
    MemorySurfaceHealth,
    MemorySurfaceRole,
    MigrationStatus,
    ReadMode,
    RiskLevel,
    SurfaceCategory,
    SurfaceStatus,
    TruthState,
    WriteMode,
)
from dharma_swarm.memory_kernel.census import CensusConfig, CensusResult, MemorySurfaceCensus
from dharma_swarm.memory_kernel.context_admission import (
    MemoryContextBudget,
    MemoryContextPack,
    MemoryContextPackItem,
    preview_memory_pack,
    render_memory_context_pack_markdown,
)
from dharma_swarm.memory_kernel.context_eval import (
    ContextEvalConfig,
    ContextEvalLane,
    ContextEvalReport,
    ContextEvalSeverity,
    ContextSafetyFinding,
    CurrentContextLaneReport,
    MemoryKernelContextLaneReport,
    evaluate_current_context_text,
    evaluate_memory_kernel_context,
    run_context_eval,
)
from dharma_swarm.memory_kernel.context_eval_cases import (
    ContextEvalCase,
    ContextEvalCaseResult,
    default_context_eval_cases,
    run_context_eval_case,
    run_default_context_eval_cases,
)
from dharma_swarm.memory_kernel.context_eval_render import render_context_eval_markdown
from dharma_swarm.memory_kernel.facade import MemoryKernel, MemoryKernelConfig
from dharma_swarm.memory_kernel.surfaces import SurfaceSpec, default_surface_specs
from dharma_swarm.memory_kernel.writers import (
    DiscoveredMemoryWrite,
    DiscoveredWriteStatus,
    DiscoveryTriageCategory,
    MemoryWriterObservation,
    MemoryWriterSentinel,
    MemoryWriterSpec,
    WriterClassification,
    WriterSentinelSummary,
    WriterStatus,
    WriterDiscoverySummary,
    default_writer_specs,
)

__all__ = [
    "AdapterMode",
    "AuthorityLevel",
    "CensusConfig",
    "CensusResult",
    "DiscoveredMemoryWrite",
    "DiscoveredWriteStatus",
    "DiscoveryTriageCategory",
    "MemoryAtom",
    "MemoryAtomType",
    "MemoryContextBudget",
    "MemoryContextPack",
    "MemoryContextPackItem",
    "ContextEvalConfig",
    "ContextEvalLane",
    "ContextEvalReport",
    "ContextEvalCase",
    "ContextEvalCaseResult",
    "ContextEvalSeverity",
    "ContextSafetyFinding",
    "CurrentContextLaneReport",
    "MemoryLane",
    "MemoryOrder",
    "MemoryQuery",
    "MemoryScope",
    "MemoryKernel",
    "MemoryKernelConfig",
    "MemorySurface",
    "MemorySurfaceCensus",
    "MemorySurfaceHealth",
    "MemorySurfaceRole",
    "MemoryKernelContextLaneReport",
    "MemoryWriterObservation",
    "MemoryWriterSentinel",
    "MemoryWriterSpec",
    "MigrationStatus",
    "ReadMode",
    "RiskLevel",
    "SurfaceCategory",
    "SurfaceSpec",
    "SurfaceStatus",
    "TruthState",
    "WriteMode",
    "WriterClassification",
    "WriterDiscoverySummary",
    "WriterSentinelSummary",
    "WriterStatus",
    "default_surface_specs",
    "default_writer_specs",
    "default_context_eval_cases",
    "evaluate_current_context_text",
    "evaluate_memory_kernel_context",
    "preview_memory_pack",
    "render_context_eval_markdown",
    "render_memory_context_pack_markdown",
    "run_context_eval_case",
    "run_default_context_eval_cases",
    "run_context_eval",
]
