"""Compatibility exports for the Palantir Pilot public surface."""

from __future__ import annotations

from dharma_swarm.palantir_pilot_manifest import (
    AGENT_ID,
    CALLSIGN,
    CONTEXT_ENGINEERING_FILE,
    DATABASE_SOURCE_KINDS,
    DEFAULT_DHARMA_HOME,
    DISPLAY_NAME,
    DOC_FAMILY_PREFIXES,
    FORBIDDEN_ACTIONS,
    MEMORY_PLANE_DB,
    NATS_SUBJECT,
    OWNED_SURFACES,
    PUBLIC_SOURCES,
    QUERY_CONSUMER,
    RAW_SOURCE_DIR,
    REPO_AGENT_HOME,
    REPO_ROOT,
    SCHEMA_VERSION,
    SEED_FILE,
    SOUL_FILE,
    VERIFIER_COMMANDS,
    WIKI_HOME,
    WIKI_SOURCE_DIR,
    build_external_worker_registration,
    build_source_manifest,
    format_markdown,
    latest_source_index_path,
    memory_plane_db_path,
    summarize_source_families,
    write_manifest_json,
    write_wiki_home,
)
from dharma_swarm.palantir_pilot_query import (
    _load_latest_source_index,
    build_answer_packet,
    build_answer_packet_from_query_packet,
    build_query_packet,
    index_workspace_to_memory_plane,
    query_source_index,
    query_wiki_notes,
    record_query_packet_to_memory_plane,
)


__all__ = [
    "AGENT_ID",
    "CALLSIGN",
    "CONTEXT_ENGINEERING_FILE",
    "DATABASE_SOURCE_KINDS",
    "DEFAULT_DHARMA_HOME",
    "DISPLAY_NAME",
    "DOC_FAMILY_PREFIXES",
    "FORBIDDEN_ACTIONS",
    "MEMORY_PLANE_DB",
    "NATS_SUBJECT",
    "OWNED_SURFACES",
    "PUBLIC_SOURCES",
    "QUERY_CONSUMER",
    "RAW_SOURCE_DIR",
    "REPO_AGENT_HOME",
    "REPO_ROOT",
    "SCHEMA_VERSION",
    "SEED_FILE",
    "SOUL_FILE",
    "VERIFIER_COMMANDS",
    "WIKI_HOME",
    "WIKI_SOURCE_DIR",
    "_load_latest_source_index",
    "build_answer_packet",
    "build_answer_packet_from_query_packet",
    "build_external_worker_registration",
    "build_query_packet",
    "build_source_manifest",
    "format_markdown",
    "index_workspace_to_memory_plane",
    "latest_source_index_path",
    "memory_plane_db_path",
    "query_source_index",
    "query_wiki_notes",
    "record_query_packet_to_memory_plane",
    "summarize_source_families",
    "write_manifest_json",
    "write_wiki_home",
]
