"""Session-status and AgentOps packet contracts shared by governance tools."""

from . import receipt
from .contract import (
    CANONICAL_FIRST_READ,
    canonical_first_read_manifest,
    canonical_packet_json,
    current_utc_time,
    detect_surface_collisions,
    matching_patterns,
    normalize_repo_pattern,
    packet_digest,
    parse_gate,
    parse_work_packet,
    path_matches_pattern,
    resolve_external_dir,
)
from .models import (
    AUTHORITY_PRECEDENCE,
    RECEIPT_SCHEMA_V1,
    RECEIPT_SCHEMA_V2,
    SESSION_ENTRY_SCHEMA_V1,
    AgentOpsError,
    ApprovalPolicy,
    CollisionRecord,
    CommitPolicy,
    ConfigError,
    GateSpec,
    LoadedReceipt,
    OnboardingContractError,
    ReceiptValidationError,
    ScopeState,
    SessionEntry,
    UnsupportedReceiptSchema,
    WorkPacket,
    _VOLATILE_KEYS,
)
from .receipt import compute_stable_digest, load_receipt

__all__ = [
    "AUTHORITY_PRECEDENCE",
    "CANONICAL_FIRST_READ",
    "RECEIPT_SCHEMA_V1",
    "RECEIPT_SCHEMA_V2",
    "SESSION_ENTRY_SCHEMA_V1",
    "AgentOpsError",
    "ApprovalPolicy",
    "CollisionRecord",
    "CommitPolicy",
    "ConfigError",
    "GateSpec",
    "LoadedReceipt",
    "OnboardingContractError",
    "ReceiptValidationError",
    "ScopeState",
    "SessionEntry",
    "UnsupportedReceiptSchema",
    "WorkPacket",
    "_VOLATILE_KEYS",
    "canonical_first_read_manifest",
    "canonical_packet_json",
    "compute_stable_digest",
    "current_utc_time",
    "detect_surface_collisions",
    "load_receipt",
    "matching_patterns",
    "normalize_repo_pattern",
    "packet_digest",
    "parse_gate",
    "parse_work_packet",
    "path_matches_pattern",
    "receipt",
    "resolve_external_dir",
]
